
model_path: "models/A4_P1500/model010000.pt"
image_size: 224
class_cond: False
learn_sigma: False
num_channels: 64
num_res_blocks: 1
channel_mult: ""
num_heads: 4
num_head_channels: -1
num_heads_upsample: -1
attention_resolutions: "16"
dropout: 0.0
diffusion_steps: 1000
noise_schedule: "linear"
timestep_respacing: ""
use_kl: False
predict_xstart: False
rescale_timesteps: True
rescale_learned_sigmas: False
use_checkpoint: False
use_scale_shift_norm: True
resblock_updown: True
use_fp16: False
use_new_attention_order: False
in_channels: 1
range_t: 0
